import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PrimeReactProvider } from 'primereact/api'; 
import ApiProvider from "@/context/ApiContext"
import Footer from "@/app/components/Footer.jsx";
import { ClerkProvider } from '@clerk/nextjs'
// import 'primereact/resources/themes/bootstrap4-dark-blue/theme.css';
import 'primereact/resources/themes/lara-light-blue/theme.css'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Guardian Search",
  description: "Generated by Kormir",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
    <ClerkProvider>
     <ApiProvider>
        <PrimeReactProvider >   
          <body className={inter.className}>{children}<Footer/></body>
        </PrimeReactProvider>
      </ApiProvider>
      </ClerkProvider>
    </html>
  );
}
