import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PrimeReactProvider } from 'primereact/api'; 
import ApiProvider from "@/context/ApiContext"
import Footer from "@/components/Footer.jsx";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Guardian Search",
  description: "Generated by Kormir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <ApiProvider>
        <PrimeReactProvider >   
          <body className={inter.className}>{children}<Footer/></body>
        </PrimeReactProvider>
      </ApiProvider>
    </html>
  );
}
